# Generated by Django 3.2.10 on 2021-12-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
