# Generated by Django 3.2.10 on 2021-12-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='foto4',
        ),
    ]
