# Generated by Django 3.2.10 on 2022-01-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_local_foto4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
