# Generated by Django 3.2.10 on 2022-01-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_local_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=55),
        ),
    ]
